### PR TITLE
Fixed Idiomatic Errors

### LINKED ISSUE #61: Idiomatic Errors in the codebase
There are quite a few idiomatic errors in the code-base which do not follow the Kotlin Guidelines

### PR DESCRIPTION
**Pull request by humbletechy**
Fixes #61 

Fixed Idiomatic Errors throughout the code-base. Didn't fix the private variables errors because they are already handled in #49

### CODE REVIEW

**Comment by yashk2000** [comment]
@humbletechy could you please resolve the conflicts over here?

**Comment by humbletechy** [comment]
@yashk2000 I am currently really busy with my project, if it's not that urgent can I resolve it as soon as I get some time.

**Comment by yashk2000** [comment]
@humbletechy  since you're busy, how about I open a new pr with the issues fixed and add you as a co-author so that you are associated with the commit?
Please let me know if that's fine. That way work will be completed fast and you won't need to spend a lot of time as well.

**Comment by humbletechy** [comment]
@yashk2000 Yes sure that would be fine with me

**Comment by yashk2000** [comment]
@humbletechy great!!

**Comment by yashk2000** [comment]
Continued in https://github.com/openMF/ppi-vision/pull/93

**Pull request closed without merging**
