### PR TITLE
Fix #14 - Loss of survey option selected

### LINKED ISSUE #14: Loss of survey option selected when user swipes to next question and returns to the same question.
Whenever an answer option is selected in the app for a survey question, when the user swipes to the next question and returns back, we no longer see the selected option as selected.

### PR DESCRIPTION
**Pull request by OussEmaDevCode**
Fixes #14 

## Screenshots
video2gif_20200120_163848

### CODE REVIEW

**Comment by OussEmaDevCode** [comment]
@apoorva-mk Hi, please have a look !!

**Comment by apoorva-mk** [comment]
@OussEmaDevCode you haven't pushed the new commits/changes I believe :P

**Comment by OussEmaDevCode** [comment]
@apoorva-mk Hi : ), can you please elaborate on your query, that commit contains all the changes I have made to fix the issue !

**Comment by apoorva-mk** [comment]
Hi, the changes requested in the review are yet to be made. I will be able to approve only after that.

**Comment by OussEmaDevCode** [comment]
@apoorva-mk Sorry, but I didn't really understand what do you mean by "you haven't pushed the new commits/changes"

**Comment by apoorva-mk** [comment]
Your commit needs some changes, so please do them before I can approve.

**Comment by OussEmaDevCode** [comment]
@apoorva-mk And can you please tell me what are these changes ?

**Comment by apoorva-mk** [comment]
I have started a review for the PR, look into that.

**Comment by OussEmaDevCode** [comment]
@apoorva-mk I am sorry, but I can't really see any review, can you make sure you have published it ?

**Comment by apoorva-mk** [comment]
> @apoorva-mk I am sorry, but I can't really see any review, can you make sure you have published it ?

Oh sorry about that, I hadn't submitted them yet.

**Comment by OussEmaDevCode** [comment]
@apoorva-mk The minus sign before the line means that I have removed it (the variable is not present in the file anymore) !!

**Comment by OussEmaDevCode** [comment]
@apoorva-mk then I guess it's great time to approve the [task](https://codein.withgoogle.com/dashboard/task-instances/5491468978880512/)

**Comment by OussEmaDevCode** [comment]
Thank you very much !!

**Comment by apoorva-mk** [comment]
I believe it has been approved. Again, apologies for not being very attentive towards it!

**Comment by OussEmaDevCode** [comment]
@apoorva-mk Also, I've been trying to contact you lately for your opinion on some additions I am trying to implement to ppi vision but all my attempts were unsuccessful, can you please tell me which communication platform do you prefer ?

**Comment by OussEmaDevCode** [comment]
I personally think [gitter](https://gitter.im/OussEmaDevCode) would be great !

**Comment by apoorva-mk** [comment]
> I personally think [gitter](https://gitter.im/OussEmaDevCode) would be great !

Alright, I will try to keep up on gitter. I might have not been very attentive due to my inbox being flooded with lots of emails!

**Comment by OussEmaDevCode** [comment]
@apoorva-mk Thank you, I have already sent a message there, you are welcome to have a look !!

**Pull request merged**
